### ISSUE TITLE
Testing a function that can only be executed by another contract (Mocking)

### ISSUE THREAD

**Issue by JoseMiguelHerrera** [MeadowSuite/Meadow#15]
Hi there,

I'm loving MeadowSuite so far, but I'm wondering how to test functions that are only successfully called by other contracts (not a user)

I know the answer is probably some kind of mocking - is there something being developed that could do this? Any strategies that I could try?

Thanks

**Comment by zone117x** [comment]
Meadow does not provide any mechanism for directly invoking such functions. I suggest using mock sol contracts and the coverage blacklist so as not to include them in the test report.
