### ISSUE TITLE
npm windows install fails for meadow.CLI

### ISSUE THREAD

**Issue by inukaeth** [MeadowSuite/Meadow#17]
Installed it as follows, meadow is in the path. However executing meadow fails with the msg below.
Thanks

dotnet tool install -g meadow.cli

C:\WINDOWS\system32>where meadow
C:\Users\inuka\.dotnet\tools\meadow.exe

C:\WINDOWS\system32>meadow

Unhandled Exception: System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Meadow.Cli.Program.RunPwshForOutput(String[] pwshArgs) in /home/buildagent/teamcity-agent/work/398bd9ff1c171c94/src/Meadow.Cli/Program.cs:line 106
   at Meadow.Cli.Program.Main(String[] args) in /home/buildagent/teamcity-agent/work/398bd9ff1c171c94/src/Meadow.Cli/Program.cs:line 17

**Comment by zone117x** [comment]
Have you installed powershell core as required here? https://github.com/MeadowSuite/Meadow/wiki/Using-the-CLI#requirements

**Comment by inukaeth** [comment]
I have.

I reinstalled it along with .net core for good measure. Still getting the same issue

**Comment by zone117x** [comment]
This is the code where that exception is occurring. https://github.com/MeadowSuite/Meadow/blob/master/src/Meadow.Cli/Program.cs#L72
It is unable to find `pwsh` from your path. 
If you open Command Prompt and run `where pwsh` what do you see?

**Comment by inukaeth** [comment]
I had accidentally installed the preview which has the command as pwsh-preview.cmd. Installed the standard release and it works now!

Apologizes for that. Thanks again for the prompt help, and keeping a great product going.
