### ISSUE TITLE
Cant run truffle tests against Test.Node

### ISSUE THREAD

**Issue by bitcoinbrisbane** [MeadowSuite/Meadow#5]
I'm running the Test.Node via:

`dotnet restore`
`dotnet run --port -m "correct horse battery staple"`

But I get no results when running

`truffle test`

In PostMan I can confirm the end point is up and running via:
`{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":1}`

**Comment by zone117x** [comment]
This should be fixed in the develop branch with this commit
https://github.com/MeadowSuite/Meadow/commit/7a6261082328fe3ca81e0d42c431407edf1d73d0

**Comment by bitcoinbrisbane** [comment]
I’ll give that branch a try

**Comment by zone117x** [comment]
Is this working for you now?

**Comment by bitcoinbrisbane** [comment]
I received the following:  
```
eth_getBlockByNumber
"latest"
false
{
  "code": -32000,
  "message": "Could not convert string to boolean: latest. Path 'params[0]', line 1, position 74.",
  "data": {
    "exception": "Newtonsoft.Json.JsonReaderException: Could not convert string to boolean: latest. Path 'params[0]', line 1, position 74.\n   at Newtonsoft.Json.JsonReader.ReadBooleanString(String s)\n   at Newtonsoft.Json.JsonReader.ReadAsBoolean()\n   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)\n   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)\n   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)\n   at Meadow.JsonRpc.Server.JsonRpcHttpServer.ProcessServerHandler(RpcRequestItem item) in /home/lucascullen/GitHub/Meadow/src/Meadow.JsonRpc.Server/JsonRpcHttpServer.cs:line 410"
  }
}

```

**Comment by zone117x** [comment]
Ugh, damn losely defined types in RPC spec. I've only tested with the 'truffle unbox metacoin' example and it worked. Can you identify and post the truffle test that is triggering a eth_getBlockByNumber call? I should be able to fix this pretty quickly.

**Comment by bitcoinbrisbane** [comment]
I’ll try and debug it too. On Linux/VS code TestNode threw an exception when I tried to debug, but most likely an environment thing. I’ll try with rider or Windows

**Comment by zone117x** [comment]
Found the issue, it was just a param mismatch. 
Fixed in https://github.com/MeadowSuite/Meadow/commit/974e3e62f20e04a0f626c9ebd5cf18cfdc879506

Can you confirm?

**Comment by zone117x** [comment]
Cool. Closing this issue. Let me know if you run into any other issues.
